"""Ed25519 package signing and verification for Cascadia OS mission packages.

LocalSigner reads a private key from disk (Sprint 2B dev implementation).
Verifier holds a public key map and verifies signatures without private keys.
The Signer protocol allows Sprint 5 to swap LocalSigner for a Signing Worker
client without changing verifier code.
"""
from __future__ import annotations

import base64
import json
import os
from pathlib import Path
from typing import Protocol

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
    Ed25519PublicKey,
)
from cryptography.hazmat.primitives.serialization import (
    Encoding,
    NoEncryption,
    PrivateFormat,
    PublicFormat,
)

from cascadia.depot.canonicalization import canonical_manifest_bytes

_DEFAULT_KEY_PATH = Path.home() / ".config" / "zyrcon" / "signing.key"
_DEFAULT_BUNDLE_PATH = Path(__file__).parent / "zyrcon_signing_keys.json"

_ENV_KEY_PATH = "ZYRCON_SIGNING_KEY_PATH"
_ENV_BUNDLE_PATH = "ZYRCON_SIGNING_KEY_BUNDLE_PATH"


class Signer(Protocol):
    """Abstract signing interface. Sprint 5 Signing Worker implements this."""

    def sign(self, message: bytes) -> bytes: ...
    def key_id(self) -> str: ...


class LocalSigner:
    """Ed25519 signer using a local private key file.

    Key path: ZYRCON_SIGNING_KEY_PATH env var, or ~/.config/zyrcon/signing.key.
    Sprint 5 replaces this with a Signing Worker client without changing Verifier.
    """

    def __init__(self, key_path: str | None = None, _key_id: str | None = None) -> None:
        path = Path(key_path or os.environ.get(_ENV_KEY_PATH, str(_DEFAULT_KEY_PATH)))
        raw = path.read_bytes()
        # Try raw 32-byte seed first (generated by generate_signing_key.py),
        # then fall back to PEM format.
        if len(raw) == 32:
            self._private_key = Ed25519PrivateKey.from_private_bytes(raw)
        else:
            from cryptography.hazmat.primitives.serialization import load_pem_private_key
            self._private_key = load_pem_private_key(raw, password=None)
        self._key_id = _key_id or "local-dev"

    def sign(self, message: bytes) -> bytes:
        return self._private_key.sign(message)

    def key_id(self) -> str:
        return self._key_id

    def public_key_b64(self) -> str:
        """Return base64url-encoded public key (no padding) for key bundle."""
        pub = self._private_key.public_key()
        raw = pub.public_bytes(Encoding.Raw, PublicFormat.Raw)
        return base64.urlsafe_b64encode(raw).rstrip(b"=").decode()


class Verifier:
    """Ed25519 verifier. Holds a map of key_id → public_key.

    Used by CREW at install time. Never holds private keys.
    """

    def __init__(self, key_bundle_path: str | None = None) -> None:
        bundle_path = Path(
            key_bundle_path
            or os.environ.get(_ENV_BUNDLE_PATH, str(_DEFAULT_BUNDLE_PATH))
        )
        self._key_map: dict[str, Ed25519PublicKey] = {}
        if bundle_path.exists():
            raw_bundle = json.loads(bundle_path.read_text(encoding="utf-8"))
            for kid, b64_pub in raw_bundle.items():
                padding = 4 - len(b64_pub) % 4
                pub_bytes = base64.urlsafe_b64decode(b64_pub + "=" * (padding % 4))
                self._key_map[kid] = Ed25519PublicKey.from_public_bytes(pub_bytes)

    @classmethod
    def from_bundle(cls, bundle: dict[str, str]) -> "Verifier":
        """Create a Verifier from an in-memory key_id → base64url-public-key dict."""
        v = cls.__new__(cls)
        v._key_map = {}
        for kid, b64_pub in bundle.items():
            padding = 4 - len(b64_pub) % 4
            pub_bytes = base64.urlsafe_b64decode(b64_pub + "=" * (padding % 4))
            v._key_map[kid] = Ed25519PublicKey.from_public_bytes(pub_bytes)
        return v

    def verify(self, message: bytes, signature_b64: str, key_id: str) -> bool:
        """Verify an Ed25519 signature. Returns True if valid.

        Raises ValueError if key_id is not in the key map.
        Returns False if the signature is invalid.
        """
        if key_id not in self._key_map:
            raise ValueError(f"unknown key_id: {key_id!r}")
        padding = 4 - len(signature_b64) % 4
        sig_bytes = base64.urlsafe_b64decode(signature_b64 + "=" * (padding % 4))
        try:
            self._key_map[key_id].verify(sig_bytes, message)
            return True
        except InvalidSignature:
            return False

    def known_key_ids(self) -> list[str]:
        return list(self._key_map.keys())


def load_key_bundle(path: str) -> dict[str, str]:
    """Load key_id → base64url-encoded-public-key map from JSON file."""
    return json.loads(Path(path).read_text(encoding="utf-8"))


def sign_manifest(manifest: dict, signer: Signer) -> dict:
    """Return manifest with signature fields added.

    Sets signed_by, signature_algorithm, key_id from signer, then computes
    canonical bytes (which include those fields but exclude 'signature'),
    signs them, and returns the manifest with 'signature' added.
    """
    kid = signer.key_id()
    # Assemble the pre-signature manifest with all final metadata fields.
    m = {**manifest, "signed_by": kid, "signature_algorithm": "Ed25519", "key_id": kid}
    m.pop("signature", None)  # strip any stale signature before computing canonical bytes
    canon = canonical_manifest_bytes(m)  # also strips 'signature', but belt-and-suspenders
    sig_bytes = signer.sign(canon)
    sig_b64 = base64.urlsafe_b64encode(sig_bytes).rstrip(b"=").decode()
    m["signature"] = sig_b64
    return m


def verify_manifest(manifest: dict, verifier: Verifier) -> bool:
    """Verify manifest signature. Returns True if valid.

    Raises ValueError if key_id is unknown.
    Returns False if the signature does not verify.
    """
    key_id = manifest.get("key_id", "")
    sig_b64 = manifest.get("signature", "")
    canon = canonical_manifest_bytes(manifest)
    return verifier.verify(canon, sig_b64, key_id)
